on: pull_request

jobs:
  close:
    name: Close Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo sha is $GITHUB_SHA
        curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/ImJasonH/nopr-2/commits/$GITHUB_SHA/pulls
