on: pull_request

jobs:
  close:
    name: Close Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Find all open PRs, and close them.
        env
        echo ---
        echo $GITHUB_REPOSITORY
        set -euxo pipefail
        prs=$(curl https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=open | grep "^    \"number\": " | grep -Eo "([0-9]+)")
        for p in $prs; do
          curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -d '{"state":"closed"}' https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$p
        done
