on: pull_request

jobs:
  close:
    name: Close Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Find all open PRs, and close them.
        set -euxo pipefail
        sudo apt-get update && sudo apt-get install jq
        curl https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=open | jq '.[].number' | xargs -I{} curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -d '{"state":"closed"}' https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/{}
