on: pull_request

jobs:
  close:
    name: Close Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euxo pipefail
        prs=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/ImJasonH/nopr-2/pulls?state=open | \
          grep "^    \"id\":" | cut -d':' -f2 | cut -d' ' -f2 | cut -d',' -f1)
        echo Open PRs: $prs
        # xargs -I{} curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -d '{"state":"closed"}' https://api.github.com/repos/ImJasonH/nopr-2/pulls/{}
	for p in $prs; do echo closing $p; done
